theme = "monokai_pro_spectrum"

[editor]
line-number = "relative"
mouse = true
true-color = true
color-modes = true
bufferline = "multiple"
completion-replace = true
completion-trigger-len = 4
cursorline = true
# cursorcolumn = true

[editor.lsp]
enable = true
display-messages = true

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "position", "separator"]
center = ["version-control", "file-name", "spinner", "diagnostics"]
right = ["separator", "total-line-numbers", "file-type", "file-encoding"]
separator = "┆"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = false
character = "▏" # Some characters that work well: "╎", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
C-t = ":theme catppuccin_latte"
C-j = ":theme monokai_pro_spectrum"
C-s = ":w"
C-x = ":bc"
C-r = ":config-reload"